
=====
===== LOGGING STARTED Fri Apr 26 17:30:16 CEST 2024
=====

=====
===== LOGGING STARTED Fri Apr 26 17:30:16 CEST 2024
=====
Erlang/OTP 27 [RELEASE CANDIDATE 3] [erts-14.2.4] [source] [64-bit] [smp:1:1] [ds:1:1:1] [async-threads:1] [jit:ns]

Erlang/OTP 27 [RELEASE CANDIDATE 3] [erts-14.2.4] [source] [64-bit] [smp:1:1] [ds:1:1:1] [async-threads:1] [jit:ns]

Logger - error: {removed_failing_handler,default}
Failed to write log message to stdout, trying stderr
=CRASH REPORT==== 26-Apr-2024::17:30:17.615539 ===
  crasher:
    initial call: peer:init_supervision/2
    pid: <0.71.0>
    registered_name: peer_supervision
    exception exit: {peer_channel_terminated,killed}
      in function  peer:loop_supervision/1 (peer.erl, line 1303)
      in call from peer:init_supervision/2 (peer.erl, line 1281)
    ancestors: [kernel_sup,<0.47.0>]
    message_queue_len: 0
    messages: []
    links: [<0.49.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 29
    reductions: 81
  neighbours:

Kernel pid terminated (application_controller) ("{application_terminated,kernel,shutdown}")

Crash dump is being written to: /buildroot/otp/lib/stdlib/make_test_dir/stdlib_erl_crash.dump...done

=====
===== LOGGING STARTED Fri Apr 26 17:30:34 CEST 2024
=====

=====
===== LOGGING STARTED Fri Apr 26 17:30:34 CEST 2024
=====
Erlang/OTP 27 [RELEASE CANDIDATE 3] [erts-14.2.4] [source] [64-bit] [smp:1:1] [ds:1:1:1] [async-threads:1] [jit:ns]

Erlang/OTP 27 [RELEASE CANDIDATE 3] [erts-14.2.4] [source] [64-bit] [smp:1:1] [ds:1:1:1] [async-threads:1] [jit:ns]

Eshell V14.2.4 (press Ctrl+G to abort, type help(). for help)
(peer_SUITE-attached_test-569858-11861@d4ac5f6ce8e9)1> =CRASH REPORT==== 26-Apr-2024::17:30:35.920542 ===
  crasher:
    initial call: peer:init_supervision/2
    pid: <0.71.0>
    registered_name: peer_supervision
    exception exit: {peer_channel_terminated,killed}
      in function  peer:loop_supervision/1 (peer.erl, line 1303)
      in call from peer:init_supervision/2 (peer.erl, line 1281)
    ancestors: [kernel_sup,<0.47.0>]
    message_queue_len: 0
    messages: []
    links: [<0.49.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 29
    reductions: 81
  neighbours:

=SUPERVISOR REPORT==== 26-Apr-2024::17:30:35.935741 ===
    supervisor: {local,kernel_sup}
    errorContext: child_terminated
    reason: {peer_channel_terminated,killed}
    offender: [{pid,<0.71.0>},
               {id,peer_supervision},
               {mfargs,{peer,start_supervision,[]}},
               {restart_type,permanent},
               {significant,false},
               {shutdown,1000},
               {child_type,worker}]

=SUPERVISOR REPORT==== 26-Apr-2024::17:30:35.935906 ===
    supervisor: {local,kernel_sup}
    errorContext: shutdown
    reason: reached_max_restart_intensity
    offender: [{pid,<0.71.0>},
               {id,peer_supervision},
               {mfargs,{peer,start_supervision,[]}},
               {restart_type,permanent},
               {significant,false},
               {shutdown,1000},
               {child_type,worker}]

Kernel pid terminated (application_controller) ("{application_terminated,kernel,shutdown}")

Crash dump is being written to: /buildroot/otp/lib/stdlib/make_test_dir/stdlib_erl_crash.dump...done
