<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Unexpected I/O log</title>
<meta http-equiv="cache-control" content="no-cache"></meta>
<meta http-equiv="content-type" content="text/html; charset=utf-8"></meta>
<link rel="stylesheet" href="../../ct_default.css" type="text/css"></link>
<script type="text/javascript" src="../../jquery-latest.js"></script>
<script type="text/javascript" src="../../jquery.tablesorter.min.js"></script>
</head>
<body>

<br />
<h3>Unexpected I/O</h3>
<pre>

</pre>
<div class="error_logger"><pre><b>*** System report during multi_call_parallel in gen_server_SUITE 2024-11-12 09:33:26.125 ***</b>
=ERROR REPORT==== 12-Nov-2024::09:33:26.125143 ===
** Generic server my_test_name terminating 
** Last message in was stop
** When Server state == {formatted,[]}
** Reason for termination ==
** stopped
** Client <0.243969.0> stacktrace
** [{gen_server,mc_recv,5,[{file,"gen_server.erl"},{line,1973}]},
    {gen_server,multi_call,4,[{file,"gen_server.erl"},{line,1934}]},
    {gen_server_SUITE,multicall,1,[{file,"gen_server_SUITE.erl"},{line,1487}]},
    {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1794}]},
    {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1303}]},
    {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1235}]}]


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during multi_call_parallel in gen_server_SUITE 2024-11-12 09:33:26.125 ***</b>
=CRASH REPORT==== 12-Nov-2024::09:33:26.125637 ===
  crasher:
    initial call: gen_server_SUITE:init/1
    pid: <0.243973.0>
    registered_name: my_test_name
    exception exit: stopped
      in function  gen_server:handle_msg/6 (gen_server.erl, line 2426)
    ancestors: [<0.243969.0>]
    message_queue_len: 0
    messages: []
    links: [<0.243969.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 2586
    stack_size: 29
    reductions: 6882
  neighbours:


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during multi_call_parallel in gen_server_SUITE 2024-11-12 09:33:26.947 ***</b>
=WARNING REPORT==== 12-Nov-2024::09:33:26.947196 ===
'global' at node test_server@0cb284567840 requested disconnect from node 'gen_server_SUITE-multicall_remote-363716-11808@0cb284567840' in order to prevent overlapping partitions

</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during gen_server_SUITE:spec_init/1 2024-11-12 09:34:04.274 ***</b>
=ERROR REPORT==== 12-Nov-2024::09:34:04.274529 ===
** Generic server hurra terminating 
** Last message in was {'EXIT',&lt;0.248320.0&gt;,
                               {#Ref&lt;0.1825156640.3035627521.218127&gt;,1007597,
                                ok,
                                [{gen_server_SUITE,spec_init}],
                                []}}
** When Server state == {formatted,{}}
** Reason for termination ==
** {#Ref&lt;0.1825156640.3035627521.218127&gt;,1007597,ok,
    [{gen_server_SUITE,spec_init}],
    []}


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during gen_server_SUITE:spec_init/1 2024-11-12 09:34:04.275 ***</b>
=CRASH REPORT==== 12-Nov-2024::09:34:04.274909 ===
  crasher:
    initial call: gen_server_SUITE:spec_init_global_default_timeout/2
    pid: &lt;0.248341.0&gt;
    registered_name: []
    exception exit: {#Ref&lt;0.1825156640.3035627521.218127&gt;,1007597,ok,
                     [{gen_server_SUITE,spec_init}],
                     []}
      in function  gen_server:decode_msg/9 (gen_server.erl, line 2299)
    ancestors: [&lt;0.248320.0&gt;]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 4185
    stack_size: 29
    reductions: 4757
  neighbours:


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during log_mf_h_SUITE:test/1 2024-11-12 09:38:42.169 ***</b>
=CRASH REPORT==== 12-Nov-2024::09:38:42.168815 ===
  crasher:
    initial call: gen_event:init_it/6
    pid: &lt;0.254110.0&gt;
    registered_name: []
    exception exit: {#Ref&lt;0.1825156640.3037200385.1126&gt;,5785,
                     {ok,3},
                     [{log_mf_h_SUITE,test}],
                     []}
      in function  gen_event:terminate_server/4 (gen_event.erl, line 1694)
    ancestors: [&lt;0.254108.0&gt;]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 6772
    stack_size: 29
    reductions: 28117
  neighbours:


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during dist in peer_SUITE 2024-11-12 09:38:51.690 ***</b>
=ERROR REPORT==== 12-Nov-2024::09:38:51.690050 ===
** Generic server <0.255396.0> terminating 
** Last message in was {nodedown,'peer_down_crash-446179-11808@0cb284567840'}
** When Server state == {peer_state,
                            #{args => ["-connect_all","false"],
                              name => "peer_down_crash-446179-11808",
                              peer_down => crash},
                            'peer_down_crash-446179-11808@0cb284567840',
                            [47,98,117,105,108,100,114,111,111,116,47,111,116,
                             112,47,69,114,108,97,110,103,32,8709,8868,8478,
                             47,101,114,116,115,45,49,53,46,49,46,50,47,98,
                             105,110,47,101,114,108],
                            ["-sname","peer_down_crash-446179-11808",
                             "-connect_all","false","-detached",
                             "-peer_detached","-user","peer","-origin",
                             "g1h3GHRlc3Rfc2VydmVyQDBjYjI4NDU2Nzg0MAAD5aQAAAAAZzMQiA=="],
                            undefined,undefined,<<>>,
                            {down,
                                {nodedown,
                                    'peer_down_crash-446179-11808@0cb284567840'}},
                            {<0.255390.0>,#Ref<0.1825156640.3030384642.47673>},
                            0,#{}}
** Reason for termination ==
** {nodedown,'peer_down_crash-446179-11808@0cb284567840'}


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during dist in peer_SUITE 2024-11-12 09:38:51.690 ***</b>
=CRASH REPORT==== 12-Nov-2024::09:38:51.690625 ===
  crasher:
    initial call: peer:init/1
    pid: <0.255396.0>
    registered_name: []
    exception exit: {nodedown,'peer_down_crash-446179-11808@0cb284567840'}
      in function  gen_server:handle_common_reply/8 (gen_server.erl, line 2476)
    ancestors: [<0.255390.0>]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 4185
    stack_size: 29
    reductions: 11200
  neighbours:


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during dist in peer_SUITE 2024-11-12 09:38:52.604 ***</b>
=WARNING REPORT==== 12-Nov-2024::09:38:51.602917 ===
Process <0.91.0> on node 'peer_SUITE-shutdown_stop-354341-11808@0cb284567840' enabled access to the emulator internal state.
NOTE: This is an erts internal test feature and should *only* be used by OTP test-suites.



</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during dist in peer_SUITE 2024-11-12 09:38:53.227 ***</b>
=WARNING REPORT==== 12-Nov-2024::09:38:53.227072 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_stop_timeout-354309-11808@0cb284567840'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during dist in peer_SUITE 2024-11-12 09:38:53.357 ***</b>
=WARNING REPORT==== 12-Nov-2024::09:38:53.357025 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_halt_timeout-446467-11808@0cb284567840'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during tcp in peer_SUITE 2024-11-12 09:39:09.721 ***</b>
=WARNING REPORT==== 12-Nov-2024::09:39:08.720071 ===
Process <0.88.0> on node 'peer_SUITE-shutdown_stop-365924-11808@0cb284567840' enabled access to the emulator internal state.
NOTE: This is an erts internal test feature and should *only* be used by OTP test-suites.



</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during tcp in peer_SUITE 2024-11-12 09:39:09.728 ***</b>
=WARNING REPORT==== 12-Nov-2024::09:39:09.728922 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_halt_timeout-588066-11808@0cb284567840'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during tcp in peer_SUITE 2024-11-12 09:39:10.185 ***</b>
=WARNING REPORT==== 12-Nov-2024::09:39:10.185123 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_stop_timeout-365892-11808@0cb284567840'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2024-11-12 09:39:12.860 ***</b>
=ERROR REPORT==== 12-Nov-2024::09:39:12.860527 ===
** Generic server <0.255759.0> terminating 
** Last message in was {'EXIT',<0.255757.0>,
                               {#Ref<0.1825156640.3029860356.242337>,1559874,
                                ok,
                                [{peer_SUITE,cntrl_channel_handler_crash}],
                                []}}
** When Server state == {peer_state,#{name =>
                                          "peer_SUITE-cntrl_channel_handler_crash-366148-11808",
                                      connection => standard_io},
                                    'peer_SUITE-cntrl_channel_handler_crash-366148-11808@0cb284567840',
                                    [47,98,117,105,108,100,114,111,111,116,47,
                                     111,116,112,47,69,114,108,97,110,103,32,
                                     8709,8868,8478,47,101,114,116,115,45,49,
                                     53,46,49,46,50,47,98,105,110,47,101,114,
                                     108],
                                    ["-sname",
                                     "peer_SUITE-cntrl_channel_handler_crash-366148-11808",
                                     "-user","peer"],
                                    #Port<0.3122>,undefined,<<>>,running,
                                    {<0.255757.0>,
                                     #Ref<0.1825156640.3030122499.119557>},
                                    0,#{}}
** Reason for termination ==
** {#Ref<0.1825156640.3029860356.242337>,1559874,ok,
    [{peer_SUITE,cntrl_channel_handler_crash}],
    []}


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during standard_io in peer_SUITE 2024-11-12 09:39:12.861 ***</b>
=CRASH REPORT==== 12-Nov-2024::09:39:12.861088 ===
  crasher:
    initial call: peer:init/1
    pid: <0.255759.0>
    registered_name: []
    exception exit: {#Ref<0.1825156640.3029860356.242337>,1559874,ok,
                     [{peer_SUITE,cntrl_channel_handler_crash}],
                     []}
      in function  gen_server:decode_msg/9 (gen_server.erl, line 2299)
    ancestors: [<0.255757.0>]
    message_queue_len: 1
    messages: [{'EXIT',#Port<0.3122>,normal}]
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 4185
    stack_size: 29
    reductions: 14084
  neighbours:


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2024-11-12 09:39:13.749 ***</b>
=WARNING REPORT==== 12-Nov-2024::09:39:12.747945 ===
Process <0.88.0> on node 'peer_SUITE-shutdown_stop-447203-11808@0cb284567840' enabled access to the emulator internal state.
NOTE: This is an erts internal test feature and should *only* be used by OTP test-suites.



</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2024-11-12 09:39:13.978 ***</b>
=WARNING REPORT==== 12-Nov-2024::09:39:13.978144 ===
peer:stop() timed out waiting for disconnect from node 'init_debug-354821-11808@0cb284567840'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2024-11-12 09:39:14.168 ***</b>
=WARNING REPORT==== 12-Nov-2024::09:39:14.168040 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_halt_timeout-447139-11808@0cb284567840'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2024-11-12 09:39:14.226 ***</b>
=WARNING REPORT==== 12-Nov-2024::09:39:14.225941 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_stop_timeout-447171-11808@0cb284567840'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2024-11-12 09:39:15.346 ***</b>
=ERROR REPORT==== 12-Nov-2024::09:39:15.346321 ===
** Generic server <0.255781.0> terminating 
** Last message in was {'EXIT',<0.255740.0>,
                           {#Ref<0.1825156640.3029860356.242269>,4047740,ok,
                            [{peer_SUITE,
                                 cntrl_channel_handler_crash_old_release}],
                            []}}
** When Server state == {peer_state,#{args =>
                                          ["-setcookie",
                                           "DUGJNPLNFQAYZCCJSXWO","-pa",
                                           "/buildroot/otp/lib/stdlib/make_test_dir/stdlib_test",
                                           "-env","ERL_CRASH_DUMP",
                                           "/buildroot/otp/lib/stdlib/make_test_dir/ct_logs/ct_run.test_server@0cb284567840.2024-11-12_09.23.35/erl_crash_dump.peer_SUITE-cntrl_channel_handler_crash_old_release-447235-11808",
                                           "-pa",
                                           "/buildroot/otp/lib/stdlib/make_test_dir/ct_logs/ct_run.test_server@0cb284567840.2024-11-12_09.23.35/make_test_dir.stdlib_test.logs/run.2024-11-12_09.24.12/log_private/"],
                                      env => [{"ERL_AFLAGS",false}],
                                      name =>
                                          "peer_SUITE-cntrl_channel_handler_crash_old_release-447235-11808",
                                      connection => standard_io,
                                      exec =>
                                          "/usr/local/lib/erlang-25.3.2.15/bin/erl",
                                      start_cover => false},
                                    'peer_SUITE-cntrl_channel_handler_crash_old_release-447235-11808@0cb284567840',
                                    "/usr/local/lib/erlang-25.3.2.15/bin/erl",
                                    ["-sname",
                                     "peer_SUITE-cntrl_channel_handler_crash_old_release-447235-11808",
                                     "-setcookie","DUGJNPLNFQAYZCCJSXWO",
                                     "-pa",
                                     "/buildroot/otp/lib/stdlib/make_test_dir/stdlib_test",
                                     "-env","ERL_CRASH_DUMP",
                                     "/buildroot/otp/lib/stdlib/make_test_dir/ct_logs/ct_run.test_server@0cb284567840.2024-11-12_09.23.35/erl_crash_dump.peer_SUITE-cntrl_channel_handler_crash_old_release-447235-11808",
                                     "-pa",
                                     "/buildroot/otp/lib/stdlib/make_test_dir/ct_logs/ct_run.test_server@0cb284567840.2024-11-12_09.23.35/make_test_dir.stdlib_test.logs/run.2024-11-12_09.24.12/log_private/",
                                     "-user","peer"],
                                    #Port<0.3143>,undefined,<<>>,running,
                                    {<0.255740.0>,
                                     #Ref<0.1825156640.3037200385.20152>},
                                    0,#{}}
** Reason for termination ==
** {#Ref<0.1825156640.3029860356.242269>,4047740,ok,
    [{peer_SUITE,cntrl_channel_handler_crash_old_release}],
    []}


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during standard_io in peer_SUITE 2024-11-12 09:39:15.347 ***</b>
=CRASH REPORT==== 12-Nov-2024::09:39:15.347151 ===
  crasher:
    initial call: peer:init/1
    pid: <0.255781.0>
    registered_name: []
    exception exit: {#Ref<0.1825156640.3029860356.242269>,4047740,ok,
                     [{peer_SUITE,cntrl_channel_handler_crash_old_release}],
                     []}
      in function  gen_server:decode_msg/9 (gen_server.erl, line 2299)
    ancestors: [<0.255740.0>]
    message_queue_len: 1
    messages: [{'EXIT',#Port<0.3143>,normal}]
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 17731
    stack_size: 29
    reductions: 18969
  neighbours:


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during supervisor_SUITE:temporary_bystander/1 2024-11-12 10:00:44.915 ***</b>
=ERROR REPORT==== 12-Nov-2024::10:00:44.915387 ===
** Generic server <0.332506.0> terminating 
** Last message in was {'EXIT',<0.332503.0>,
                               {#Ref<0.1825156640.3068657665.172313>,350593,
                                [{child1,<0.332512.0>,worker,[]}],
                                [{supervisor_SUITE,temporary_bystander}],
                                []}}
** When Server state == {state,
                            {<0.332506.0>,supervisor_SUITE},
                            rest_for_one,
                            {[child1],
                             #{child1 =>
                                   {child,<0.332512.0>,child1,
                                       {supervisor_1,start_child,[]},
                                       permanent,false,100,worker,[]}}},
                            undefined,2,300,
                            [-576458523],
                            0,never,supervisor_SUITE,
                            {ok,{{rest_for_one,2,300},[]}}}
** Reason for termination ==
** {#Ref<0.1825156640.3068657665.172313>,350593,
    [{child1,<0.332512.0>,worker,[]}],
    [{supervisor_SUITE,temporary_bystander}],
    []}


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during supervisor_SUITE:temporary_bystander/1 2024-11-12 10:00:44.916 ***</b>
=ERROR REPORT==== 12-Nov-2024::10:00:44.915393 ===
** Generic server <0.332505.0> terminating 
** Last message in was {'EXIT',<0.332503.0>,
                               {#Ref<0.1825156640.3068657665.172313>,350593,
                                [{child1,<0.332512.0>,worker,[]}],
                                [{supervisor_SUITE,temporary_bystander}],
                                []}}
** When Server state == {state,
                            {<0.332505.0>,supervisor_SUITE},
                            one_for_all,
                            {[child1],
                             #{child1 =>
                                   {child,<0.332511.0>,child1,
                                       {supervisor_1,start_child,[]},
                                       permanent,false,100,worker,[]}}},
                            undefined,2,300,
                            [-576458523],
                            0,never,supervisor_SUITE,
                            {ok,{{one_for_all,2,300},[]}}}
** Reason for termination ==
** {#Ref<0.1825156640.3068657665.172313>,350593,
    [{child1,<0.332512.0>,worker,[]}],
    [{supervisor_SUITE,temporary_bystander}],
    []}


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during supervisor_SUITE:temporary_bystander/1 2024-11-12 10:00:44.916 ***</b>
=CRASH REPORT==== 12-Nov-2024::10:00:44.916056 ===
  crasher:
    initial call: supervisor:supervisor_SUITE/1
    pid: <0.332506.0>
    registered_name: []
    exception exit: {#Ref<0.1825156640.3068657665.172313>,350593,
                     [{child1,<0.332512.0>,worker,[]}],
                     [{supervisor_SUITE,temporary_bystander}],
                     []}
      in function  gen_server:decode_msg/9 (gen_server.erl, line 2299)
    ancestors: [<0.332503.0>]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 4185
    stack_size: 29
    reductions: 14806
  neighbours:


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during supervisor_SUITE:temporary_bystander/1 2024-11-12 10:00:44.916 ***</b>
=CRASH REPORT==== 12-Nov-2024::10:00:44.916563 ===
  crasher:
    initial call: supervisor:supervisor_SUITE/1
    pid: <0.332505.0>
    registered_name: []
    exception exit: {#Ref<0.1825156640.3068657665.172313>,350593,
                     [{child1,<0.332512.0>,worker,[]}],
                     [{supervisor_SUITE,temporary_bystander}],
                     []}
      in function  gen_server:decode_msg/9 (gen_server.erl, line 2299)
    ancestors: [<0.332503.0>]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 4185
    stack_size: 29
    reductions: 14836
  neighbours:


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during zzz_SUITE:lc_graph/1 2024-11-12 10:27:29.709 ***</b>
=WARNING REPORT==== 12-Nov-2024::10:27:29.707015 ===
Process <0.436106.0> on node 'test_server@0cb284567840' enabled access to the emulator internal state.
NOTE: This is an erts internal test feature and should *only* be used by OTP test-suites.



</pre></div>
<pre>
</pre>
<center>
<br /><hr /><p>
<a href="../../../all_runs.html">Test run history
</a>  |  <a href="../../../index.html">Top level test index
</a>  |  <a href="../../../suite.log.latest.html">Latest test result</a>
</p>
<div class="copyright">Copyright &copy; 2024 <a href="http://www.erlang.org">Open Telecom Platform</a><br />
Updated: <!--date-->Tue Nov 12 2024 09:24:12<!--/date--><br />
</div>
</center>
</body>
</html>
