<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Test config_func_error_1_SUITE:exit_in_eptc result</title>
<meta http-equiv="cache-control" content="no-cache"></meta>
<meta http-equiv="content-type" content="text/html; charset=utf-8"></meta>
<link rel="stylesheet" href="../../ct_default.css" type="text/css"></link>
<script type="text/javascript" src="../../jquery-latest.js"></script>
<script type="text/javascript" src="../../jquery.tablesorter.min.js"></script>
</head>
<body>

<a name="top"></a><pre>
=== Test case: <a href="config_func_error_1_suite.src.html#exit_in_eptc-1">config_func_error_1_SUITE:exit_in_eptc/1</a> (click for source code)

=== Config value:

    [{watchdog,&lt;0.3752.0&gt;},
     {tc_logfile,"/buildroot/otp/lib/common_test/make_test_dir/ct_logs/ct_run.test_server@74d7103eabd8.2024-10-28_14.17.48/make_test_dir.common_test_test.logs/run.2024-10-28_14.17.50/log_private/ct_run.ct@74d7103eabd8.2024-10-28_14.29.23/ct_error_SUITE_data.error.config_func_error_1_SUITE.logs/run.2024-10-28_14.29.23/config_func_error_1_suite.exit_in_eptc.1187.html"},
     {tc_group_properties,[{name,g2}]},
     {tc_group_path,[]},
     {data_dir,"/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_error_SUITE_data/error/test/config_func_error_1_SUITE_data/"},
     {priv_dir,"/buildroot/otp/lib/common_test/make_test_dir/ct_logs/ct_run.test_server@74d7103eabd8.2024-10-28_14.17.48/make_test_dir.common_test_test.logs/run.2024-10-28_14.17.50/log_private/ct_run.ct@74d7103eabd8.2024-10-28_14.29.23/ct_error_SUITE_data.error.config_func_error_1_SUITE.logs/run.2024-10-28_14.29.23/log_private/"}]

=== Current directory is "/buildroot/otp/lib/common_test/make_test_dir/ct_logs/ct_run.test_server@74d7103eabd8.2024-10-28_14.17.48/make_test_dir.common_test_test.logs/run.2024-10-28_14.17.50/log_private/ct_run.ct@74d7103eabd8.2024-10-28_14.29.23"

=== Started at 2024-10-28 14:29:24

<br />
ct_test_support *generating* error of type 'THROW'

</pre>
<div class="default"><pre><b>*** User 2024-10-28 14:29:24.134 ***</b><a id=e-9 class="link-to-entry" href="#e-9">&#x1f517;</a>
Bye bye from &lt;0.3755.0&gt;
</pre></div>
<pre>
=== WARNING! config_func_error_1_SUITE:end_per_testcase(exit_in_eptc, [{tc_status,
                                                                    ok},
                                                                   {watchdog,
                                                                    &lt;0.3754.0&gt;},
                                                                   {tc_logfile,
                                                                    "/buildroot/otp/lib/common_test/make_test_dir/ct_logs/ct_run.test_server@74d7103eabd8.2024-10-28_14.17.48/make_test_dir.common_test_test.logs/run.2024-10-28_14.17.50/log_private/ct_run.ct@74d7103eabd8.2024-10-28_14.29.23/ct_error_SUITE_data.error.config_func_error_1_SUITE.logs/run.2024-10-28_14.29.23/config_func_error_1_suite.exit_in_eptc.1187.html"},
                                                                   {tc_group_properties,
                                                                    [{name,
                                                                      g2}]},
                                                                   {tc_group_path,
                                                                    []},
                                                                   {data_dir,
                                                                    "/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_error_SUITE_data/error/test/config_func_error_1_SUITE_data/"},
                                                                   {priv_dir,
                                                                    "/buildroot/otp/lib/common_test/make_test_dir/ct_logs/ct_run.test_server@74d7103eabd8.2024-10-28_14.17.48/make_test_dir.common_test_test.logs/run.2024-10-28_14.17.50/log_private/ct_run.ct@74d7103eabd8.2024-10-28_14.29.23/ct_error_SUITE_data.error.config_func_error_1_SUITE.logs/run.2024-10-28_14.29.23/log_private/"}]) failed!
	Reason: {'EXIT',{nocatch,generated_throw}}


</pre>
<div class="sasl"><pre><b>*** System report during config_func_error_1_SUITE:exit_in_eptc/1 in g2 2024-10-28 14:29:24.135 ***</b><a id=e-10 class="link-to-entry" href="#e-10">&#x1f517;</a>
=ERROR REPORT==== 28-Oct-2024::14:29:24.135019 ===
Error in process &lt;0.3755.0&gt; on node ct@74d7103eabd8 with exit value:
{{nocatch,generated_throw},
 [{ct_test_support,'-random_error/1-fun-2-',2,
                   [{file,"ct_test_support.erl"},{line,452}]},
  {config_func_error_1_SUITE,bad_proc,1,
                             [{file,"config_func_error_1_SUITE.erl"},
                              {line,79}]}]}


</pre></div>
<pre>
<a name="end"></a>


=== Ended at 2024-10-28 14:29:24
=== successfully completed test case
=== === Returned value: ok
</pre>
<center>
<br /><hr /><p>
<a href="../../../all_runs.html">Test run history
</a>  |  <a href="../../../index.html">Top level test index
</a>  |  <a href="../../../suite.log.latest.html">Latest test result</a>
</p>
<div class="copyright">Copyright &copy; 2024 <a href="http://www.erlang.org">Open Telecom Platform</a><br />
Updated: <!--date-->Mon Oct 28 2024 14:29:24<!--/date--><br />
</div>
</center>
</body>
</html>
